//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControleAcesso
    {
        public int Id { get; set; }
        public int IdPessoa { get; set; }
        public System.DateTime DataAcesso { get; set; }
        public string TipoAcesso { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
