//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foto
    {
        public int Id { get; set; }
        public int IdPessoa { get; set; }
        public string Nome { get; set; }
        public Nullable<long> Tamanho { get; set; }
        public string Tipo { get; set; }
        public byte[] FileContent { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
