//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CadastroEventoBdEntities : DbContext
    {
        public CadastroEventoBdEntities()
            : base("name=CadastroEventoBdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ControleAcesso> ControleAcesso { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<EventoDia> EventoDia { get; set; }
        public virtual DbSet<Pessoa> Pessoa { get; set; }
        public virtual DbSet<TipoPessoa> TipoPessoa { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Foto> Foto { get; set; }
    }
}
