//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public Pessoa()
        {
            this.ControleAcesso = new HashSet<ControleAcesso>();
            this.EventoDia = new HashSet<EventoDia>();
            this.Foto = new HashSet<Foto>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public int IdTipoPessoa { get; set; }
        public string Empresa { get; set; }
        public string Cargo { get; set; }
        public string CPF { get; set; }
        public string Telefone { get; set; }
        public string Celular { get; set; }
        public string CNPJ { get; set; }
        public string CEP { get; set; }
        public string Endereco { get; set; }
        public string Numero { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<ControleAcesso> ControleAcesso { get; set; }
        public virtual TipoPessoa TipoPessoa { get; set; }
        public virtual ICollection<EventoDia> EventoDia { get; set; }
        public virtual ICollection<Foto> Foto { get; set; }
    }
}
